export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';



export const ITEM_UPDATE = 'ITEM_UPDATE';
export const ITEM_CREATE = 'ITEM_CREATE';
export const ITEMS_FETCH_START = 'ITEMS_FETCH_START';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const ITEM_SAVE_SUCCESS = 'ITEM_SAVE_SUCCESS';

export const OWNER_UPDATE = 'OWNER_UPDATE';
export const OWNER_CREATE = 'OWNER_CREATE';
export const OWNER_FETCH_START = 'OWNERS_FETCH_START';
export const OWNER_FETCH_SUCCESS = 'OWNERS_FETCH_SUCCESS';
export const OWNER_SAVE_SUCCESS = 'OWNER_SAVE_SUCCESS';


export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_REMOVE = 'ITEM_REMOVE';
export const ITEM_CHECK = 'ITEM_CHECK';
export const ITEM_UNCHECK = 'ITEM_UNCHECK';
export const ITEM_FORM_EMPTY = 'ITEM_FORM_EMPTY';
